import { Save } from "lucide-react";
import { useState } from "react";
import { useApp } from "../../context/AppContext";
import { PageTitle } from "./AdminDashboard";

export default function ContentPage() {
  const { content, saveContent } = useApp();
  const [draft, setDraft] = useState(content);
  const [saved, setSaved] = useState(false);
  const update = (key, value) => { setSaved(false); setDraft((current) => ({ ...current, [key]: value })); };
  const updateJson = (key, value) => { try { update(key, JSON.parse(value)); } catch { setDraft((current) => ({ ...current, [`${key}_raw`]: value })); } };
  async function submit(event) { event.preventDefault(); const clean = { ...draft }; delete clean.services_raw; delete clean.gallery_raw; delete clean.testimonials_raw; await saveContent(clean); setSaved(true); }
  return <><PageTitle eyebrow="Website" title="Content manager" text="Update the public landing page content and business WhatsApp configuration." /><form className="mt-6 grid gap-5" onSubmit={submit}><section className="card grid gap-4 p-5"><h2 className="font-black">Hero section</h2><Field label="Main headline"><input className="field" value={draft.hero_title} onChange={(e) => update("hero_title", e.target.value)} /></Field><Field label="English description"><textarea className="field" rows="3" value={draft.hero_subtitle} onChange={(e) => update("hero_subtitle", e.target.value)} /></Field><Field label="Spanish description"><textarea className="field" rows="3" value={draft.hero_spanish} onChange={(e) => update("hero_spanish", e.target.value)} /></Field><Field label="Hero image URL"><input className="field" value={draft.hero_image} onChange={(e) => update("hero_image", e.target.value)} /></Field><Field label="Owner WhatsApp number"><input className="field" placeholder="Country code + number" value={draft.whatsapp_number} onChange={(e) => update("whatsapp_number", e.target.value)} /></Field></section><section className="card grid gap-4 p-5"><h2 className="font-black">Page collections</h2><p className="text-xs leading-relaxed text-slate-500">Edit these JSON collections to manage services, gallery photos, and testimonials. Keep the existing structure for each item.</p><JsonField label="Services" value={draft.services_raw ?? JSON.stringify(draft.services, null, 2)} onChange={(value) => updateJson("services", value)} /><JsonField label="Gallery image URLs" value={draft.gallery_raw ?? JSON.stringify(draft.gallery, null, 2)} onChange={(value) => updateJson("gallery", value)} /><JsonField label="Testimonials" value={draft.testimonials_raw ?? JSON.stringify(draft.testimonials, null, 2)} onChange={(value) => updateJson("testimonials", value)} /></section><div className="flex items-center gap-3"><button className="btn-primary"><Save size={17} /> Save content</button>{saved && <p className="text-sm font-bold text-green-600">Content saved.</p>}</div></form></>;
}
function Field({ label, children }) { return <label><span className="label">{label}</span>{children}</label>; }
function JsonField({ label, value, onChange }) { return <Field label={label}><textarea className="field font-mono text-xs" rows="7" value={value} onChange={(e) => onChange(e.target.value)} /></Field>; }
